dist: trusty

language: php
php:
  # using major version aliases
  - 5.5
  - 5.6
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini

script:
  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -d error_reporting=E_ALL -d display_errors=On -l | grep -v "No syntax errors detected"; then exit 1; fi

matrix:
  fast_finish: true

jobs:
  include:
    - stage: deploy
      script:
        - wget -O phpdoc.phar http://phpdoc.org/phpDocumentor.phar
        - php phpdoc.phar -d core/ -t docs/ --ignore core/views/ --title "Slid Docs" --template="xml"
        - composer require "evert/phpdoc-md"
        - git clone https://github.com/Skayo/slid.wiki.git slid-wiki
        - phpdocmd docs/structure.xml slid-wiki
        - cd slid-wiki
        - git remote add origin https://SkayoBot:{$GITHUB_ACCESS_TOKEN}@github.com/Skayo/slid.wiki.git
        - git add .
        - git commit -m "Updated API Docs with PHPdoc"
        - git push
      php: 7.0
