dist: trusty

language: php
php:
  # using major version aliases
  - 5.5
  - 5.6
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini

script:
  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -d error_reporting=E_ALL -d display_errors=On -l | grep -v "No syntax errors detected"; then exit 1; fi

matrix:
  fast_finish: true

jobs:
  include:
    - stage: deploy
      install:
        - wget -O phpdoc.phar http://phpdoc.org/phpDocumentor.phar
        - composer global require "evert/phpdoc-md"
      before_script:
        - git clone https://github.com/Skayo/slid.wiki.git slid-wiki
      script:
        - php phpdoc.phar -d core/ -t docs/ --ignore core/views/ --title "Slid Docs" --template="xml"
        - /home/travis/.composer/vendor/bin/phpdocmd docs/structure.xml slid-wiki --index "Classes.md" --lt "%c"
        - find slid-wiki -name "*.md"
        - php -r 'print_r(glob("slid-wiki/*.md"));'
        - find slid-wiki -name "*.md" | php -R 'file_put_contents($argn, html_entity_decode(file_get_contents($argn)));'
      after_success:
        - cd slid-wiki
        - git config user.email "frederike.gnampf@gmail.com"
        - git config user.name "SkayoBot"
        - git add .
        - git commit -m "Updated API Docs with PHPDoc"
        - git remote rm origin
        - git remote add origin https://${GITHUB_ACCESS_TOKEN}@github.com/Skayo/slid.wiki.git
        - git push -u origin master
      php: 7.0
